# Generated by Django 4.0.5 on 2022-06-26 16:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 26, 16, 24, 54, 183601, tzinfo=utc)),
        ),
    ]
